import { ArxivPaper } from "./arxiv";

/**
 * Mermaid visualization payload returned by the conceptual dive endpoint.
 */
export interface Visualization {
  /** Mermaid visualization category used by the UI for icon/label selection. */
  type: 'mindmap' | 'timeline' | 'architecture' | 'flowchart' | 'sequence' | 'quadrant';
  /** Mermaid source code used for client-side rendering. */
  code: string;
  /** Human-readable chart title. */
  title: string;
  /** Short description of what the chart represents. */
  description: string;
}

/**
 * Normalized conceptual dive payload consumed by the Conceptual Dive tab.
 */
export interface ConceptualAnalysis {
  /** Narrative cross-paper comparison generated by Gemini. */
  comparison: string;
  /** Structured visual comparison artifacts in Mermaid form. */
  visualizations: Visualization[];
  /** Focused analysis of figures, metrics, and technical specifications. */
  figuresAnalysis: string;
}

/**
 * Performs a conceptual dive for selected arXiv papers by calling the backend
 * conceptual-dive endpoint and normalizing the response shape for UI safety.
 *
 * Normalization guarantees:
 * - Missing `comparison` and `figuresAnalysis` fields become empty strings.
 * - Missing or invalid `visualizations` becomes an empty array.
 *
 * @param papers Selected arXiv papers to analyze.
 * @returns Normalized conceptual analysis payload.
 * @throws Error when the backend returns a non-2xx response.
 */
export async function performConceptualDive(papers: ArxivPaper[]): Promise<ConceptualAnalysis> {
  const response = await fetch("/api/gemini/conceptual-dive", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ papers }),
  });

  const rawText = await response.text();
  let payload: Partial<ConceptualAnalysis> & { details?: string } = {};

  try {
    payload = rawText ? JSON.parse(rawText) : {};
  } catch {
    payload = {};
  }

  if (!response.ok) {
    const details = typeof payload.details === "string"
      ? payload.details
      : rawText || `HTTP ${response.status} ${response.statusText}`;
    throw new Error(details);
  }

  return {
    comparison: typeof payload.comparison === "string" ? payload.comparison : "",
    figuresAnalysis: typeof payload.figuresAnalysis === "string" ? payload.figuresAnalysis : "",
    visualizations: Array.isArray(payload.visualizations) ? payload.visualizations : [],
  };
}
